collections:
  projects:
    output: true
    # sort_by: order
    permalink: :collection/:name
baseurl: "" # the subpath of your site, e.g. /blog/
relative_url: ""
url: "https://haniehst.github.io/" # the base hostname & protocol for your site
markdown: kramdown
